title: "Mi Web"
description: "Mi sitio web usando Jekyll"
baseurl: "/Intento-1.github.io"  # Si no usas subdirectorios adicionales, dejar vacío
permalink: /:path/  # Mantiene la estructura de carpetas para las URLs
